version: 0.2

phases:
  pre_build:
    commands:
      - echo Fazendo login no ECR... comando sugeridos no console do ECR , repositorio e obotão "View push commands"     
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 241585213334.dkr.ecr.us-east-1.amazonaws.com
      - echo Definindo variáveis de ambiente... para utilização no build e post_build
      - REPOSITORY_URI=241585213334.dkr.ecr.us-east-1.amazonaws.com/bia
      - echo Definindo a tag da imagem com os 7 primeiros caracteres do hash do commit ou "latest" caso não seja possível obter o hash
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build iniciado em `date`
      - echo Gerando imagem da BIA...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Explicacao: iniciando etapa post_build
      - echo Build finalizado com sucesso em `date`
      - echo Fazendo push da imagem para o ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Gerando artefato da imagem para o ECS
      - echo Criando imagedefinitions.json com name e imageUri para deploy no ECS
      - printf '[{"name":"bia-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json

